config/routes.rb
Rails.application.routes.draw do
  resources :abouts

  resources :news_faqs

  resources :ministries

  mount RailsAdmin::Engine => '/amagara', as: 'rails_admin'
  resources :homes

  root :to=>'pages#index'

  devise_for :users

  get "pages/children"
  get "pages/descipleship"
  get "pages/education"
  get "pages/vocational"
  get "pages/news"
  get "pages/faqs"
  get "pages/about"
  get "pages/who"

end

app/models/home.rb
class Home < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @homes = Home.all
    respond_with(@homes)
  end

  def show
    respond_with(@home)
  end

  def new
    @home = Home.new
    respond_with(@home)
  end

  def edit
  end

  def create
    @home = Home.new(home_params)
    @home.save
    respond_with(@home)
  end

  def update
    @home.update(home_params)
    respond_with(@home)
  end

  def destroy
    @home.destroy
    respond_with(@home)
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:title, :category, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@homes = Home.where(category: 'introduction')
  	@ministry = Home.where(category: 'ministry')
  	@aids = Home.where(category: 'news')
  end

  def children
  	@children = Ministry.where(category: 'children')
  end

  def education
  	@children = Ministry.where(category: 'children')
  end

  def vocational
  	@children = Ministry.where(category: 'children')
  end

  def descipleship
  	@children = Ministry.where(category: 'children')
  end

  def faqs
    @faqs = NewsFaq.where(category: 'faqs')
  end

  def news
    
  end

  def about
    @about = About.where(category: 'who')
  end

  def who
    @who = About.where(category: 'who')
  end

  def news
    @who = About.where(category: 'who')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/homes/_form.html.erb
<div class="container">
<%= form_for @home, :html => { :class => "form-horizontal home" } do |f| %>

    <% if @home.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @home.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@home[:title]) %>
  </div>
  
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@home[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar, :class => 'form-control' %>
    </div>
    <%= error_span(@home[:avatar]) %>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category, options_for_select(["introduction", "ministry", "donation", "news"]) %>
    </div>
    <%= error_span(@home[:category]) %>
  </div><br/>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            homes_path, :class => 'btn btn-default' %>

<% end %>

app/views/homes/edit.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/index.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= link_to home.id, home_path(home) %></td>
        <td><%= home.title %></td>
        <td><%= home.category %></td>
        <td><%= home.description %></td>
        <td><%= image_tag home.avatar.url(:thumb) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_home_path(home), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      home_path(home),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_home_path,
            :class => 'btn btn-primary' %>

app/views/homes/new.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/homes/show.html.erb
<%- model_class = Home -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @home.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @home.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @home.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= image_tag @home.avatar.url(:thumb) %></dd>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              homes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_home_path(@home), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              home_path(@home),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/_header.html.erb
<header class="site-header header-home">
    <!-- tp-bar -->
    <div class="tp-bar">
        <div class="container">
            <!-- logo -->
            <div class="logo">
                <a href="#"><%= image_tag("logo.png", :size=> '100x100')%></a>
                <a><h1 class="brand" style="color:#fff;">JUNA AMAGARA MINISTRIES</h1></a> 
            </div>  
           
            <!-- counter ends -->
            <div class="counter">
                  <p class="lead btn btn-lg btn-block btn-warning ">**Donate**
                    <a href="#"><%= image_tag("logo.png", :size=> '30x30')%></a>
                  </p>
                <div class="">
                      <p class="notice"><%= notice %></p>
                      <p class="alert"><%= alert %></p></div>
                <div class="event-bx">
					      <h4><a href="#">Juna Amagara</a></h4>
                    <ul class="options">
                    	<li><i class="icon-map-marker"></i>Addis Ababa, Ethiopia</li>
                    </ul>
                    <p>Itaque earum rerum hic tenetur a sapien delectus, ut aut reiciendis rerum hic tenet rerum hic tenetur</p>
                    <%= image_tag("logo.png", :size=> '100x100')%>
                    <div class="event-bx-btm">
                    	<a href="events.html" class="btn btn-default">View More Events</a>
                    </div>
                </div>
            </div>

            
        </div>
    </div>

    <!-- navbar Main Navigation -->
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle"
                  data-toggle="collapse"
                  data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">
          Toggle navigation
        </span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
      </div>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Home", root_path %></li>
              <li><%= link_to "Sponsorship" %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">Contruction<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                     <li><%= link_to "kishanye Mbarara" %></li>
                     <li><%= link_to "Rubanda Kabale" %></li>
                     <li><%= link_to "kayanja Hoima" %></li>
                  </ul>
              </li>

              <li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">
                      About <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "Who we are", pages_who_path%></li>
                      <li><%= link_to "About Uganda", pages_about_path %></li>
                  </ul>
              </li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">Faqs/News <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Faqs", pages_faqs_path %></li>
                    <li><%= link_to "News", pages_news_path%></li>
                  </ul>
              </li>
              
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle js-activated" data-toggle="dropdown">Ministries
                  <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Children", pages_children_path %></li>
                    <li><%= link_to "Education", pages_education_path %></li>
                    <li><%= link_to "Discipleship", pages_descipleship_path %></li>
                    <li><%= link_to "Vocational", pages_vocational_path %></li>
                  </ul>
              </li>
          </ul>
        </div>
        <div class="pull-right">
            <ul class="social-links">
                <li><a href="#" class="icon-facebook" data-placement="bottom" data-toggle="tooltip" title="" data-original-title="facebook"></a></li>
            </ul>
        </div>
        <div class="site-search">
            <span class="search-btn"></span>
            <div class="search-contain">
                <form method="post" action="#">
                    <input type="text" placeholder="Search...">
                    <input type="submit">
                </form>
            </div>
        </div>
        
    </div>
</header>
<article class="banner" style="background-image:url(assets/p.PNG);">
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Non profit making organisation in uganda">
  <meta name="author" content="Topbrainz">
  <title>Amagara</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    body{
      font-size: 160%;
    }
  </style>
</head>
<body>
<%= render :partial => 'layouts/header' %>

<%= yield %>
</div>
<%= render :partial => 'layouts/footer' %>
<script type="text/javascript">
  $(document).ready(function() {
    $('.carousel').carousel({interval: 15000});
  });
</script>
<script>
	// very simple to use!
	$(document).ready(function() {
	  $('.js-activated').dropdownHover().dropdown();
	});
</script>
</body>
</html>

app/views/pages/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="background-image:url(assets/p.PNG); color:white;">
    <!-- Carousel indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>   
    <!-- Carousel items -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="container">
                <div class="row">
                    <div class="col-md-7 col-lg-7 ">
                        <% @homes.each do |h|%>
                            <h1><%= h.title %></h1>
                            <p class="lead"><%= h.description %></p>
                            
                            <p><a class="btn btn-lg btn-warning col-md-6">Help a child, Donate now...</a></p>
                        
                    </div>
                    <div class="col-md-5 col-lg-5 ">
                        <div class="" style="margin-top:30px;">
                                <%= image_tag h.avatar.url, :size=>"500x260", :class => "img-rounded" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-12 ">
                        <%= image_tag("header image.PNG", :size=>"1150x200") %>
                    </div>
                </div>
            </div>
                    
        </div>
        <div class="item">
            <ul class="thumbnails">
                    <li class="col-lg-3">
                        <div class="thumbnail">
                            <%= image_tag("p.PNG")%>
                        </div>
                        <p>Another caption<br>
                        <small class="red">$19.99</small><br>
                        <a href="#" class="btn btn-success">Buy Now</a></p>
                    </li>
                    <li class="col-lg-3">
                        <div class="thumbnail">
                            <%= image_tag("p.PNG")%>
                        </div>
                        <p>Another caption<br>
                        <small class="red">$19.99</small><br>
                        <a href="#" class="btn btn-success">Buy Now</a></p>
                    </li>
                    <li class="col-lg-3">
                        <div class="thumbnail">
                            <%= image_tag("p.PNG")%>
                        </div>
                        <p>Another caption<br>
                        <small class="red">$19.99</small><br>
                        <a href="#" class="btn btn-success">Buy Now</a></p>
                    </li>
                    <li class="col-lg-3">
                        <div class="thumbnail">
                            <%= image_tag("p.PNG")%>
                        </div>
                        <p>Another caption<br>
                        <small class="red">$19.99</small><br>
                        <a href="#" class="btn btn-success">Buy Now</a></p>
                    </li>
                </ul>
        </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>
</div>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-8 col-lg-8 ">
            <% @aids.each do |h|%>
                <div class="container text-muted ">
                    <h2><%= h.title %></h2>
                    <%= h.description %>
                </div>
            <% end %>
        </div>
        <div class="col-md-4 col-lg-4 ">
            <iframe src="http://player.vimeo.com/video/88617114?title=0&byline=0&portrait=0&color=00b952" width="971" height="228" frameborder="0"></iframe>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <% @ministry.in_groups_of(4, false) do |four|%>
            <% four.each do |k| %>
                <div class="col-md-3 col-lg-3 mine">
                <p><%= k.title %></p>
                <%= image_tag k.avatar.url(:medium), :class => "img-rounded" %>
                </div>
            <% end %>
        <% end %>
    </div>
    
</div>